name: Check Datahub Jars

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docker/**"
      - "docs/**"
      - "**.md"
  release:
    types: [published, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  check_jars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: check datahub-client jar
        run: |
          ./gradlew :metadata-integration:java:datahub-client:build
          ./gradlew :metadata-integration:java:datahub-client:javadoc
      - name: check spark-lineage jar
        run: |
          ./gradlew :metadata-integration:java:spark-lineage:build
          ./gradlew :metadata-integration:java:spark-lineage:javadoc
