name: metadata ingestion slow integration tests
on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - master
    paths:
      - "**/nifi/**"
      - "**/nifi.py"
      - "**/hana/**"
      - "**/hana.py"
  release:
    types: [published, edited]

jobs:
  metadata-ingestion-slow-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: ./metadata-ingestion/scripts/install_deps.sh
      - name: Run metadata-ingestion slow integration tests
        run: ./gradlew :metadata-ingestion:testSlowIntegration
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test Results (metadata ingestion slow integration tests)
          path: |
            **/build/reports/tests/test/**
            **/build/test-results/test/**
            **/junit.*.xml

  event-file:
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Event File
          path: ${{ github.event_path }}
